baseurl = "//"
title = "Rugby Analysis"
author = "Arthur Gymer"
copyright = "Copyright (c) 2019 - , Arthur Gymer; all rights reserved."
canonifyurls = true
paginate = 3
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

googleAnalytics = ""

theme = "strange-case"

[params]
	colorScheme = "scheme-darkbrown"
	dateformat = "Jan 2, 2006"
	description = ""
	sidebarDescription = ""
	sidebarFreeText = "A place for all my rugby analysis and graphics"
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
	name = "Github"
	post = "<span class='glyphicon glyphicon-wrench'></span>"
	url = "https://github.com/awgymer"
